<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$platform = 'admin';
$this->headLink()->appendStylesheet("$basePath/css/$platform/reset.css")
				 ->appendStylesheet("$basePath/css/$platform/menu.css")
                 ->appendStylesheet("$basePath/css/$platform/boxes.css");

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->prependFile("$basePath/js/jquery.js", 'text/javascript');
				   //->prependFile("$basePath/js/html5.js", 'text/javascript', array('conditional' => 'lt IE9',));

echo $this->doctype('XHTML1_STRICT');
?>

<html lang="en">
<head>
	<meta charset="utf-8">
   	<?php echo $this->headTitle('ZF2 Tutorial') ?>

   	<?php echo $this->headMeta() ?>

   	<!-- Le styles -->
   	<?php echo $this->headLink() ?>
    
   	<!-- Scripts -->
   	<?php echo $this->headScript() ?>
   	
   	<script type="text/javascript">
    //<![CDATA[
	$(function(){
		$('#nav li').mouseover(function(){
			$(this).addClass('over');
		});
		$('#nav li').mouseout(function(){
			$(this).removeClass('over');
		});
	});
	//]]>
   	</script>
</head>

<body class=" <?php echo $this->route; ?>">
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<a href="<?php echo $this->url('application-admin-dashboard'); ?>">
					<img class="logo" alt="ZendStore Logo" src="/images/admin/logo.png" />
				</a>
				<div class="header-right">
					<p class="super">
						Logged in as ???
						<span class="separator"> | </span>
						Logged in date
						<span class="separator"> | </span>
						<a class="link-logout">Log out</a>
					</p>
				</div>
			</div>
			<div class="clear"></div>
			<div class="nav-bar">
				<ul id="nav">
					<li class="level0 <?php if ($this->route == 'application-admin-dashboard'): echo 'active'; endif; ?>">
						<a href="<?php echo $this->url('application-admin-dashboard') ?>"><span>Dashboard</span></a>
					</li>
	              	<li class="parent level0 <?php if ($this->route == 'catalog-admin-product' || $this->route == 'catalog-admin-category'): echo 'active'; endif; ?>">
	              		<a onclick="javascript:return false;" href="#"><span>Catalog</span></a>
	              		<ul>
			              	<li class="level1">
			              		<a href="<?php echo $this->url('catalog-admin-product', array('action' => 'add')); ?>"><span>Product</span></a>
			              	</li>
							<li class="level1">
			              		<a href="<?php echo $this->url('catalog-admin-category'); ?>"><span>Category</span></a>
			              	</li>              		
	              		</ul>
	              	</li>
	              	<li class="level0 <?php if ($this->route == 'demo-admin-test'): echo 'active'; endif; ?>">
	              		<a href="<?php echo $this->url('demo-admin-test', array('action' => 'view')); ?>"><span>Demo</span></a>
	              	</li>
	              	<li class="level0 <?php if ($this->route == 'user-admin-user'): echo 'active'; endif; ?>">
	              		<a href="<?php echo $this->url('user-admin-user'); ?>"><span>User</span></a>
	              	</li>
				</ul>
			</div>	
		</div>
		
		<div id="anchor-content" class="middle">
			<div id="page:main-container">
				<?php echo $this->content; ?>
			</div>
		</div>

		<div class="footer">
		</div>
	</div>    	
</body>
</html>
