<h2>/demo/front/demo/index</h2>

<!-- 
dl: Definition list
dt: Definition term
dd:	Definition description
-->
<dl>
	<dt><a href="<?php echo $this->url('demo-front-demo'); ?>">Index</a></dt>
<dt><a href="<?php echo $this->url('demo-front-demo', array('action' => 'disableLayout')); ?>">Disable layout, good for dealling with "ajax with html content".</a></dt>
<dt><a href="<?php echo $this->url('demo-front-demo', array('action' => 'disableView')); ?>">Disable view.</a></dt>
	<dt><a href="<?php echo $this->url('demo-front-demo', array('action' => 'disableTemplate')); ?>">Disable template(layout and view) completely, good for dealling with "ajax with json content".</a></dt>
</dl>