<script type="text/javascript" src="/js/mlselection.js"></script>
<script type="text/javascript">
$(function(){
	regionInit('region');
	
});
</script>

<p>Geography::Region::indexAction</p>

<h5>Select region - Multi-level selection:</h5>
<div id="region" jsurl="<?php echo $this->url('region', array('action' => 'listChildren')); ?>">
   	<input type="hidden" name="region_id" id="region_id" class="mls_id" />
	<input type="hidden" name="region_name" id="region_name" class="mls_names" />
    <select>
    	<option>Please select...</option>
        <?php foreach ($regions as $region): ?>
        <option value="<?php echo $region['region_id']; ?>"><?php echo $region['region_name']; ?></option>
        <?php endforeach; ?>
    </select>
</div>
