<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 Tutorial') ?>

    <?php echo $this->headMeta() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

    <script type="text/javascript" src="/js/jquery.js"></script>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div>Admin Layout</div>
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">Tutorial</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
              <li class="active"><a href="<?php echo $this->url('front-demo-test', array('action' => 'view')); ?>">FrontDemo</a></li>
              <li class="active"><a href="<?php echo $this->url('admin-demo-test', array('action' => 'view')); ?>">AdminDemo</a></li>
              <li class="active"><a href="<?php echo $this->url('album') ?>">Album</a></li>
              <li class="active"><a href="<?php echo $this->url('base') ?>">Base</a></li>
              <li class="active"><a href="<?php echo $this->url('uploader') ?>">Media</a></li>
              <li class="active"><a href="<?php echo $this->url('region') ?>">Region</a></li>
              <li class="active"><a href="<?php echo $this->url('payment') ?>">Payment</a></li>
              <li class="active"><a href="<?php echo $this->url('front-user-user'); ?>">FrontUser</a></li>
              <li class="active"><a href="<?php echo $this->url('admin-user-user'); ?>">AdminUser</a></li>
              <li class="active"><a href="<?php echo $this->url('front-catalog-category'); ?>">FrontCategory</a></li>
              <li class="active"><a href="<?php echo $this->url('admin-catalog-product', array('action' => 'add')); ?>">AdminProduct</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
