<?php
$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<?php print_r($album);?>
<p>Are you sure that you want to delete 
  '<?php echo $album->title; ?>' by 
  '<?php echo $album->artist; ?>'?
</p>
<?php 
$url = $this->url('album-front-album', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$album['id']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>