<?php 
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<p><a href="<?php echo $this->url('album-front-album', array('action'=>'add')); ?>">
    Add new album</a></p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($albums as $album) : ?>
<tr>
    <td><?php echo $album->title;?></td>
    <td><?php echo $album->artist;?></td>
    <td>
        <a href="<?php echo $this->url('album-front-album', array('action'=>'edit', 'id' => $album->id));?>">
        	Edit</a>
        <a href="<?php echo $this->url('album-front-album', array('action'=>'delete', 'id' => $album->id));?>">
        	Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
