<?php
$title = 'New product';
$this->headTitle($title);
?>

<div class="colums">
	<div id="page:left" class="side-col">
		<h3>Product Information</h3>
		<ul id="product_info_tabs" class="tabs">
			<li>
				<a name="group_4" id="product_info_tabs_group_4" class="tab-item-link active" href="#" title="General">
					<span>General</span>
				</a>
			</li>
			<li>
		        <a name="group_95" id="product_info_tabs_group_95" class="tab-item-link active" href="#" title="Description">
		            <span>Description</span>
		        </a>
		    </li>
		</ul>		
	</div>
	<div id="content" class="main-col">
	
	</div>	
</div>




<h1>Add Product</h1>
<?php
$form = $this->form;
echo $this->form()->openTag($form);
?>
<dl>
	<dt><?php echo $this->formInput($form->get('product_name')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('product_name'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('price')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('price'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('market_price')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('market_price'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('brand')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('brand'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('quantity')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('quantity'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('tags')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('tags'));?></dt>
	
	<dt><?php /*echo $this->formRadio($form->get('on_shelf')); */?></dt>
	<dt><?php echo $this->formElementErrors($form->get('on_shelf'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('category_id')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('category_id'));?></dt>

	<dt><?php echo $this->formInput($form->get('link_id')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('link_id'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('submit')); ?></dt>
</dl>
