<?php
$title = 'Edit product';
$this->headTitle($title);
?>

<h1>Edit Product</h1>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('product_id'));
echo $this->formHidden($form->get('description_id'));
?>
<dl>
	<dt><?php echo $this->formLabel($form->get('product_name')); ?></dt>
	<dt><?php echo $this->formInput($form->get('product_name')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('product_name'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('description')); ?></dt>
	<dt><?php echo $this->formTextarea($form->get('description')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('description'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('store_price')); ?></dt>
	<dt><?php echo $this->formInput($form->get('store_price')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('store_price'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('market_price')); ?></dt>
	<dt><?php echo $this->formInput($form->get('market_price')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('market_price'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('brand')); ?></dt>
	<dt><?php echo $this->formInput($form->get('brand')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('brand'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('quantity')); ?></dt>
	<dt><?php echo $this->formInput($form->get('quantity')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('quantity'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('tags')); ?></dt>
	<dt><?php echo $this->formInput($form->get('tags')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('tags'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('category_id')); ?></dt>
	<dt><?php echo $this->formInput($form->get('category_id')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('category_id'));?></dt>
	
	<dt><?php echo $this->formLabel($form->get('link_id')); ?></dt>
	<dt><?php echo $this->formInput($form->get('link_id')); ?></dt>
	<dt><?php echo $this->formElementErrors($form->get('link_id'));?></dt>
	
	<dt><?php echo $this->formInput($form->get('submit')); ?></dt>
</dl>
<?php ?>
