<?php 
$title = 'Edit category';
$this->headTitle($title);
?>

<script type="text/javascript">
//<![CDATA[
$(function(){
	// Submit category form by ajax 
	$('#save-category').click(function(e){
		e.preventDefault();
		var url = $('#category_form').attr('action');
		var params = {
			'category_id':	 $('#category_id').val(),
			'category_name': $('#category_name').val(),
			'description':   $('#description').val() 
		};
		$.post(url, params, function(data){
			$("#category-edit-container").html(data);
		});
	});
});
//]]>
</script>

<div class="content-header">
	<h3 class="icon-head head-categories">New Root Category</h3>
</div>

<ul id="category_info_tabs" class="tabs-horiz">
	<li>
		<a id="category_info_tabs_group_7" class="tab-item-link active" title="General Information" href="#">
			<span>General Information</span>
		</a>
	</li>
	<li>
		<a id="category_info_tabs_products" class="tab-item-link" title="Category Products" href="#">
			<span>Category Products</span>
		</a>
	</li>
</ul>

<!-- Category edit form -->
<?php 
$form = $this->form;
$form->setAttribute('action', 
	$this->url('catalog-admin-category', array('action' => 'edit', 'id' => $form->get('category_id')->getAttribute('value'))));
$form->prepare();
?>
<?php 
echo $this->form()->openTag($form); 
echo $this->formHidden($form->get('category_id'));
?>
	<div class="no-display"></div>
	<div id="category_tab_content">
		<div id="category_info_tabs_group_7_content" style="">
			<div class="entry-edit">
				<div class="entry-edit-head">
					<h4 class="icon-head head-edit-form fieldset-legend">General Information</h4>
				</div>
				<div id="group_7fieldset_group7" class="fieldset fieldset-wide">
					<div class="hor-scroll">
						<table class="form-list" cellspacing="0">
							<tbody>
								<tr>
									<td class="label"><?php echo $this->formLabel($form->get('category_name')); ?></td>
									<td class="value"><?php echo $this->formInput($form->get('category_name')); ?></td>
								</tr>
								<tr>
									<td class="label"><?php echo $this->formLabel($form->get('description')); ?></td>
									<td class="value"><?php echo $this->formTextarea($form->get('description')); ?></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="content-buttons form-buttons">
		<button id="save-category" class="scalable save" type="submit" title="Save">
			<span>Save</span>
		</button>
		<button id="reset-category" class="scalable" type="reset" title="Reset">
			<span>Reset</span>
		</button>
	</div>
<?php echo $this->form()->closeTag($form); ?>
<!-- /Category edit form -->
