<div class="colums">
	<div id="page:left" class="side-col">
		<div class="categories-side-col">
			<div class="content-header">
				<h3 class="icon-head head-categories">Categories</h3>
			</div>
		</div>
	</div>
	
	<div id="content" class="main-col">
		<div class="main-col-inner">
			<div id="messages"></div>
			<div id="category-edit-container" class="category-content">
				<div class="content-header">
					<h3 class="icon-head head-categories">New Root Category</h3>
				</div>			
			</div>
		</div>
	</div>
</div>