<?php 
$basePath = $this->basePath();
$platform = 'admin';
$this->headScript()->appendFile("$basePath/js/jquery.jstree/jquery.jstree.js", 'text/javascript')
				   ->appendFile("$basePath/js/jquery.jstree/_lib/jquery.cookie.js", 'text/javascript')
				   ->appendFile("$basePath/js/jquery.jstree/_lib/jquery.hotkeys.js", 'text/javascript');
?>

<script type="text/javascript">
//<![CDATA[
$(function(){
	// jstree holder
	$("#tree-holder")
		.jstree({
			"plugins": [
				"themes", "json_data", "ui", "crrm", "cookies", "dnd", "search", "types", "hotkeys", "contextmenu"            
			],
			"json_data": {
				"ajax": {
					"url": function(node){
						var url = "<?php echo $this->url('catalog-admin-category', array('action' => 'list')); ?>";
						var id  = node.attr ? node.attr("id").replace("node_", "") : 0;
						url += '/' + id;
						return url;
					}
				}
			},
			"types": {
				"types": {
					"file": {
						"icon": {
							"image": "/images/admin/tree_icons/file.png"
						}
					},
					"folder": {
						//"valid_children" : [ "folder" ],
						"icon": {
							"image": "/images/admin/tree_icons/folder.png"
						}
					},
					"drive": {
						"icon": {
							"image": "/images/admin/tree_icons/root.png"
						}
					}
				}
			}
		})
		.bind('create.jstree', function(e, data){
			//console.log(e);console.log(data);
			$.post(
				"<?php echo $this->url('catalog-admin-category', array('action' => 'add')); ?>",
				{
					'parent_id': 		data.rslt.parent.attr('id').replace('node_', ''),
					'category_name':	data.rslt.name
				},
				function(result) {
					if(result.succeed) {
						$(data.rslt.obj).attr('id', 'node_' + result.data.category_id);
					} else {
						$.jstree.rollback(data.rlbk);
					}
				}
			);
		})
		.bind("select_node.jstree", function(e, data){
			var selectedObj = data.rslt.obj;
			var nodeId  	= selectedObj.attr("id");
			var categoryId	= nodeId.replace("node_", "");
			var url	= "<?php echo $this->url('catalog-admin-category', array('action' => 'edit')); ?>";
			url += "/" + categoryId;
			$.get(url, function(data){
				$("#category-edit-container").html(data);
			});
		});

	// create categories actions
	$('#add_root_category_button').click(function(){
		$("#tree-holder").jstree("create", null, "last", { "attr" : { "rel" : "folder" } });
	});
	$('#add_subcategory_button').click(function(){

	});
});
//]]>
</script>

<div class="colums">
	<div id="page:left" class="side-col">
		<div class="categories-side-col">
			<div class="content-header">
				<h3 class="icon-head head-categories">Categories</h3>
				<button type="button" id="add_root_category_button" class="scalable add" title="Add Root Category" >
					<span>Add Root Category</span>
				</button>
				<button type="button" id="add_subcategory_button" class="scalable add" title="Add Subcategory">
					<span>Add Subcategory</span></button>
			</div>
			
			<div class="tree-actions">
            	<a href="#">Collapse All</a> <span class="separator">|</span> <a href="#">Expand All</a>
            </div>
            
            <div id="tree-holder"></div>
		</div>
	</div><!-- /side-col -->
	
	<div id="content" class="main-col">
		<div class="main-col-inner">
			<div id="messages"></div>
			<div id="category-edit-container" class="category-content">
				<!-- Content retrieved by ajax -->			
			</div>
		</div>
	</div><!-- /main-col -->
</div>
